### ISSUE TITLE
publish on PyPI?

### ISSUE THREAD

**Issue by ayushanand18** [marinebon/py-dwc-viz#17]
I think this package could be made more usable (and useful) if published on PyPI and/or Conda-Forge.

**Comment by 7yl4r** [comment]
can copy configuration from https://github.com/iobis/pyobis. details:

* https://github.com/iobis/pyobis/issues/17
* https://github.com/iobis/pyobis/issues/71

**Comment by ayushanand18** [comment]
The configurations look good. Let's go for a release.
