### ISSUE TITLE
visualization of taxa distribution (tree?) 

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/py-dwc-viz#2]
I wonder if there is a better way to visualize a distribution of different taxa. 
A plot of taxa counts is common (example below).

![image](https://user-images.githubusercontent.com/1051390/193853405-29db596e-8af2-4f3c-a366-a03350d88292.png)

However, taxa fall into a tree structure, and a visualization that includes this nuance would be more informative.
Something like:

![image](https://user-images.githubusercontent.com/1051390/193854630-b1548372-a58c-461f-ba50-8e5d900ed86b.png)

Potentially useful references:
* [ETETree](http://etetoolkit.org/) : python toolkit for visualizing tree structures

**Comment by MathewBiddle** [comment]
Not sure if it's applicable here but I've previously used https://github.com/parrt/dtreeviz to create a decision tree.

**Comment by ayushanand18** [comment]
I figured out that `plotly` has some inbuilt support with the ability to define custom paths through `sunburst` plots. 

But the OBIS data has some hierarchies that don't fit in well with all species (a single path which is suited for all can not be found easily), for example, I found that some `family` has no `order` but `class` and `subclass`. I don't know how to fit it into the plot.

**Comment by ayushanand18** [comment]
Like this notebook, the error I get in the end - [https://github.com/ayushanand18/obis-research/blob/efe52ace6571bf2052350efb0fe4a72ab8daf6b3/notebooks/florida-keys-taxonomic-dist.ipynb](https://github.com/ayushanand18/obis-research/blob/efe52ace6571bf2052350efb0fe4a72ab8daf6b3/notebooks/florida-keys-taxonomic-dist.ipynb)

**Comment by ayushanand18** [comment]
I made a temporary fix by replacing 'NaNs' with `str(None)` but that might not be the correct way to do it. Finally, I get this result for Florida Keys between 1997-2012.
![image](https://user-images.githubusercontent.com/36472216/194025422-61101def-bcb5-4566-bac5-04c1680d1f59.png)

**Comment by AbbyBenson** [comment]
You might consider following the GBIF example for how to build these https://www.gbif.org/dataset/9a71aa12-7636-4381-9986-d8f03240b277/metrics "Taxonomic Distribution of Occurrences"

**Comment by 7yl4r** [comment]
> You might consider following the GBIF example for how to build these https://www.gbif.org/dataset/9a71aa12-7636-4381-9986-d8f03240b277/metrics "Taxonomic Distribution of Occurrences"

Oooooh. That interactivity is nice. I see they are using highcharts.js to generate that. [python-highcharts](https://github.com/kyper-data/python-highcharts) might be able to help with if we wanted to recreate it exactly, but it doesn't look to be a well maintained repo. Based on the [plotly.sunburst docs](https://plotly.com/python/sunburst-charts/) it looks like those are interactive in the same way. What other inspiration can we take from GBIF's example?

It looks to me like the `NaN`-to-`str(None)` approach is working. Let's put this functionality into a method so I can do something like:

```python
dwcviz.taxa_sunburst(pyobis.OccSearch().search())
```

**Comment by ayushanand18** [comment]
Coupling this package with `pyobis` will be really interesting, and I would really like to do it.

**Comment by bbest** [comment]
This is all good stuff! The [GBIF sunburst plot](https://www.gbif.org/dataset/9a71aa12-7636-4381-9986-d8f03240b277/metrics) from @albenson-usgs looks the best!

I love the ability to explore it in all the ways:

1. On left, hierarchically in outline form.
2. On right, hovering over sunburst to get full name and occurrence count.
3. On right, click to dive deeper.
4. In upper right menu navbar, click to get treemap version.

## 1 & 2. initial sunburst & outline view

![image](https://user-images.githubusercontent.com/2837257/194318273-e7241956-17a8-4080-a25e-6fae2186d3ed.png)

## 3. dive deeper into sunburst

![image](https://user-images.githubusercontent.com/2837257/194319072-4a89682c-89c7-44a2-8378-0a5f2341b10f.png)

## 4. switch from sunburst to treemap view

![image](https://user-images.githubusercontent.com/2837257/194319247-f78b3002-f0d3-4fe8-a0dc-90ec21a75318.png)

## references

### highcharts & gbif

Here's the documentation for:

* [Sunburst | Highcharts](https://www.highcharts.com/docs/chart-and-series-types/sunburst-series)
  
It'd be worth digging into GBIF repos and asking them about it like here:

* [Visualization of gbif taxonomy and species occurrence data · Issue #728 · gbif/portal-feedback](https://github.com/gbif/portal-feedback/issues/728)

... which leads me to:

* [Search for "sunburst" at gbif/portal-feedback](https://github.com/gbif/portal-feedback/search?q=sunburst&type=issues)
* [Search for "sunburst" at gbif/portal16](https://github.com/gbif/portal16/search?q=sunburst)

And I see sunburst peppered throughout their JS and templating code with issues there.

### d3

Highcharts is proprietary, but is largely based on the open-source d3, which also has sunburst and treemap, or "icicle", visualizations:

* [Zoomable Sunburst / D3 / Observable](https://observablehq.com/@d3/zoomable-sunburst)
* [Zoomable Icicle / D3 / Observable](https://observablehq.com/@d3/zoomable-icicle)
* [Partition, Sunburst / D3 / Observable](https://observablehq.com/@d3/sunburst)

### older / other

* I previously looked at these types of plots here: [Krona plots for biodiversity, including eDNA · Issue #32 · marinebon/sdg14](https://github.com/marinebon/sdg14/issues/32)
* There are some good non-interactive trees with `ggtree` R package that could be made interactive with a Shiny app: [Chapter 6 Visual Exploration of Phylogenetic Trees | Data Integration, Manipulation and Visualization of Phylogenetic Trees](https://yulab-smu.top/treedata-book/chapter6.html)
* These "heat trees" look interesting as well: [Plotting taxonomic data | Analysis of Microbiome Data in R](https://grunwaldlab.github.io/analysis_of_microbiome_community_data_in_r/05--plotting.html)
    
![image](https://user-images.githubusercontent.com/2837257/194319919-4a7b8694-3629-41ed-a5db-7b886ec53756.png)

**Comment by bbest** [comment]
Well done @ayushanand18 with the plotly sunburst of taxonomic coverage in pr #4! 🎉 

I just want to document here the visual output of your contribution:

## sunfish (_Mola mola_)

```py
from pydwcviz import taxon
from pyobis.occurrences import OccQuery
occ = OccQuery()

# get the data and the figure object
fig = taxon.plot_dist(occ.search(scientificname = "Mola mola"))
        
# show the figure
fig.show()
```

![newplot (2)](https://user-images.githubusercontent.com/2837257/200350360-7ddf0b79-3a34-4452-948c-898e8084aace.png)

## octopuses (_Octopodiformes_)

Since the _Mola mola_ example is only for a single species, let's choose a higher level taxa that shows the sunburst breakdown by taxonomic groupings. 

For example, _Octopodiformes_ is a superorder of the subclass _Coleoidea_, comprising the octopuses and the vampire squid

```py
from pydwcviz import taxon
from pyobis.occurrences import OccQuery
occ = OccQuery()

# get the data and the figure object
o = occ.search(scientificname = "Octopodiformes")
fig = taxon.plot_dist(o)
        
# show the figure
fig.show()
```

![newplot (4)](https://user-images.githubusercontent.com/2837257/200350791-db292220-baa2-4abb-b340-59f99b5f9b96.png)

## octopuses (_Octopodiformes_), first 1000 occurrences (for fast example)

Since _Octopodiformes_ has 52,141 occurrences, let's limit to the first 1,000 occurrences so we can quickly render an example plot.

```py
from pydwcviz import taxon
from pyobis.occurrences import OccQuery
occ = OccQuery()

# get the first 1,000 occurences for the taxa
o = occ.search(scientificname = "Octopodiformes", offset = 0, size = 1000)

# generate the taxonomic distribution plot
fig = taxon.plot_dist(o)
        
# show the figure
fig.show()
```

![newplot (5)](https://user-images.githubusercontent.com/2837257/200361465-7927ed69-cf51-46c4-ab5c-3b4e21e57c00.png)

**Comment by ayushanand18** [comment]
> Well done @ayushanand18 with the plotly sunburst of taxonomic coverage in pr #4! 🎉
> 
> I just want to document here the visual output of your contribution:
> 
Thank you so much @bbest. These illustrations look pretty nice! 

I was figuring out a way to visualize the data as a taxon tree without increasing the dependencies much and keeping it simple and fast. I feel `plotly` treemaps don't hold more insights than sunburst plots, which are easy to comprehend, and thus would add redundancy if we add both. `Plotly` documents usage of `python-igraph` for creating trees but I would like to use a package that is well-documented, stable and fast. Would you suggest any?

**Comment by 7yl4r** [comment]
great work! :1st_place_medal:
